[opener]
edit = [
	{ run = 'ghostty nvim "$@"', block = false }
]

[[manager.prepend_keymap]]
on = "y"
run = [
    '''
    shell 'echo "$@" | wl-copy --type text/uri-list' --confirm
    ''',
    "yank"
]
